#!/usr/bin/env python3

from pprint import pprint
import re
import requests
import yaml
import dateutil.parser
from datetime import datetime

MAX_HOURS=24

COMMON_PATTERNS = (
    (
        "HOST_KAPUT",
        re.compile(r"'An error occurred while communicating with the remote host.'"),
    ),
    (
        "HOST_KAPUT",
        re.compile(
            r"'Unable to communicate with the remote host, since it is disconnected.'"
        ),
    ),
)


def get_inventory(log_url):
    r = requests.get(log_url + "zuul-info/inventory.yaml")
    return yaml.safe_load(r.text)


def search_error_pattern(log_url):
    founds = {}
    r = requests.get(log_url + "job-output.txt")
    for l in r.text.splitlines():
        for name, pattern in COMMON_PATTERNS:
            if pattern.search(l):
                if name not in founds:
                    founds[name] = 0
                founds[name] += 1
    return founds


url = "https://dashboard.zuul.ansible.com/api/tenant/ansible/builds?job_name=ansible-test-cloud-integration-vcenter_1esxi_with_nested-python36&limit=100"
r = requests.get(url)
builds = r.json()
results_by_host_id = {}
results_by_region = {}
results_by_age = {}
host_by_host_id = {}
for build in builds:
    delta = datetime.utcnow() - dateutil.parser.parse(build["end_time"])
    age = int(delta.seconds / 3600)
    if build["result"] in ("RETRY_LIMIT", "SKIPPED"):
        continue
    matches = None
    if build["result"] == "FAILURE":
        matches = search_error_pattern(build["log_url"])
        if not matches:
            print("not matches for log_url: {log_url}".format(log_url=build["log_url"]))
            print(
                "The failure may not be an hypervisor stability problem. We ignore it."
            )
            continue
    inventory = get_inventory(build["log_url"])
    cloud = inventory["all"]["hosts"]["esxi1"]["nodepool"]["cloud"]
    region = inventory["all"]["hosts"]["esxi1"]["nodepool"]["az"]
    host_id = inventory["all"]["hosts"]["esxi1"]["nodepool"]["host_id"]

    if age not in results_by_age:
        results_by_age[age] = {"SUCCESS": [], "FAILURE": []}
    results_by_age[age][build["result"]].append(
        {"log_url": build["log_url"], "matches": matches, "region": region}
    )

    if age > MAX_HOURS:
        continue

    if host_id not in results_by_host_id:
        host_by_host_id[host_id] = "{cloud}-{region}-{host_id}".format(
            cloud=cloud, region=region, host_id=host_id
        )
        results_by_host_id[host_id] = {"SUCCESS": [], "FAILURE": []}
    results_by_host_id[host_id][build["result"]].append(
        {"log_url": build["log_url"], "matches": matches}
    )

    if region not in results_by_region:
        results_by_region[region] = {"SUCCESS": [], "FAILURE": []}
    results_by_region[region][build["result"]].append(
        {"log_url": build["log_url"], "matches": matches}
    )

    print(
        "name={name} result={result}".format(
            name=host_by_host_id[host_id], result=build["result"]
        )
    )

print("BAD HOSTS (for last {max_hours})".format(max_hours=MAX_HOURS))
for host_id in results_by_host_id.keys():
    if len(results_by_host_id[host_id]["SUCCESS"]) < 2:
        # Not enough metrics
        continue

    rate = len(results_by_host_id[host_id]["SUCCESS"]) / (
        len(results_by_host_id[host_id]["SUCCESS"])
        + len(results_by_host_id[host_id]["FAILURE"])
    )

    if rate < 0.9:
        print(
            "name={name} (rate={rate})".format(name=host_by_host_id[host_id], rate=rate)
        )

print("GOOD HOSTS (for last {max_hours})".format(max_hours=MAX_HOURS))
for host_id in results_by_host_id.keys():
    if len(results_by_host_id[host_id]["SUCCESS"]) < 2:
        # Not enough metrics
        continue

    rate = len(results_by_host_id[host_id]["SUCCESS"]) / (
        len(results_by_host_id[host_id]["SUCCESS"])
        + len(results_by_host_id[host_id]["FAILURE"])
    )
    if rate > 0.9:
        print(
            "name={name} (rate={rate})".format(name=host_by_host_id[host_id], rate=rate)
        )

print("BY ZONE (for last {max_hours})".format(max_hours=MAX_HOURS))
for region, values in results_by_region.items():
    rate = len(values["SUCCESS"]) / (len(values["SUCCESS"]) + len(values["FAILURE"]))
    print("region={region} (rate={rate})".format(region=region, rate=rate))

print("BY AGE")
for age in sorted(results_by_age):
    values = results_by_age[age]
    rate = len(values["SUCCESS"]) / (len(values["SUCCESS"]) + len(values["FAILURE"]))
    print("age={age}h (rate={rate})".format(age=age, rate=rate, failures=values["FAILURE"]))
    for failure in values["FAILURE"]:
        print("    - {failure})".format(age=age, rate=rate, failure=failure))
